### ISSUE TITLE
Add link to your blog post referencing this repo

### ISSUE THREAD

**Issue by jrop** [ColinEberhardt/json-transforms#9]
Just thought others might find your post which references this repo helpful (as I did--thanks!):

http://blog.scottlogic.com/2016/06/22/xslt-inspired-ast-transforms.html

BTW, I really like your technique.  Thanks for the writeup!

**Comment by ColinEberhardt** [comment]
Good idea - I've added the blog post to the README: https://github.com/ColinEberhardt/json-transforms/commit/40e331ff0b584474b5077ad8549eaeb737132c8c - really glad you like it!

**Comment by jrop** [comment]
Awesome!
